name: delf_global
description: Una red social con traducción instantánea y comunicación global
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.5
  video_player: ^2.8.3
  cupertino_icons: ^1.0.6
  intl_phone_field: ^3.1.0
  http: ^1.2.2
  flutter_slidable: ^4.0.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^8.0.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  google_sign_in: ^6.1.4
  uuid: ^4.5.1
  image_picker: ^0.8.7+4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/google.png
    - assets/delf_logo.png
