// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcfcaGaaZ7NrZKyDqvITywVODNdmkiPY0',
    appId: '1:1014078666263:web:c6459181c9b6f02b00ce52',
    messagingSenderId: '1014078666263',
    projectId: 'delf-chat-global',
    authDomain: 'delf-chat-global.firebaseapp.com',
    storageBucket: 'delf-chat-global.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUfiqTZkcc5ZhFBPCPQu3SczYDJFn8Bo8',
    appId: '1:1014078666263:android:779d3db3dbdf5f8800ce52',
    messagingSenderId: '1014078666263',
    projectId: 'delf-chat-global',
    storageBucket: 'delf-chat-global.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC2i60nhGi-TTuGphWAp0vnsMtdl00RR4',
    appId: '1:1014078666263:ios:737d053fdba674d200ce52',
    messagingSenderId: '1014078666263',
    projectId: 'delf-chat-global',
    storageBucket: 'delf-chat-global.firebasestorage.app',
    iosClientId: '1014078666263-7gpm88inedbbd9ger64heo9q126q3tre.apps.googleusercontent.com',
    iosBundleId: 'com.example.delfGlobal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC2i60nhGi-TTuGphWAp0vnsMtdl00RR4',
    appId: '1:1014078666263:ios:737d053fdba674d200ce52',
    messagingSenderId: '1014078666263',
    projectId: 'delf-chat-global',
    storageBucket: 'delf-chat-global.firebasestorage.app',
    iosClientId: '1014078666263-7gpm88inedbbd9ger64heo9q126q3tre.apps.googleusercontent.com',
    iosBundleId: 'com.example.delfGlobal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcfcaGaaZ7NrZKyDqvITywVODNdmkiPY0',
    appId: '1:1014078666263:web:89c638dfb46536ac00ce52',
    messagingSenderId: '1014078666263',
    projectId: 'delf-chat-global',
    authDomain: 'delf-chat-global.firebaseapp.com',
    storageBucket: 'delf-chat-global.firebasestorage.app',
  );
}
